# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('facebookLink', models.TextField()),
                ('postID', models.TextField()),
                ('festivalName', models.TextField()),
                ('festivalDate', models.TextField()),
                ('poster', models.TextField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('identifiers', models.TextField()),
            ],
        ),
    ]
