# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOFapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('facebookLink', models.TextField()),
                ('date_DDMM', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='festivalDate',
            new_name='festivalDate_DDMMYY',
        ),
    ]
